installCRDs: true
global:
  leaderElection:
    namespace: cert-manager
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 200m
    memory: 256Mi
tolerations: 
  - key: addonskey
    effect: NoSchedule
    operator: Exists
webhook:
  tolerations: 
  - key: addonskey
    effect: NoSchedule
    operator: Exists
cainjector:
  tolerations: 
  - key: addonskey
    effect: NoSchedule
    operator: Exists
startupapicheck:
  tolerations: 
  - key: addonskey
    effect: NoSchedule
    operator: Exists
