installCRDs: true
global:
  leaderElection:
    namespace: cert-manager
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 200m
    memory: 256Mi
tolerations: 
  - key: addonskey
      effect: NoSchedule
      operator: Exists
