autoDiscovery:
  clusterName: intern_eks-test
rbac:
  ## If true, create & use RBAC resources
  ##
  create: false

  ## Ignored if rbac.create is true
  ##
  serviceAccountName: default

# autoscalingGroups: 
#  - name: asg1
#    maxSize: 3
#    minSize: 2