provider: aws
logLevel: info

sources:
  - service
  - ingress

policy: sync

registry: txt
# R53Zone ID
txtOwnerId: velvio

aws:
  region: eu-central-1
  zoneType: public
tolerations: 
  - key: addonskey
    effect: NoSchedule
    operator: Exists
domainFilters:
  - velvioo.brainscale.cloud
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::548844171305:role/dev_external_dns_role_name
