clusterName: "intern_eks-test"
clusterEndpoint: "https://D59D3CE2607BCF8B092B6E84294A65CB.gr7.us-east-1.eks.amazonaws.com"
serviceAccount:
  name: "karpenter-sa"
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::548844171305:role/intern_eks-test-cluster-karpenter-role

aws.defaultInstanceProfile: "customer-mc-ec2-instance-profile"